name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: lionzxy
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: lionzxy/charity-frontend:latest, lionzxy/charity-frontend:${{ github.run_number }}

      - name: Connect to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: charity.kulikov.uk
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /home/frontend
            cd /home/frontend
            docker-compose down
            sed 's/%%%IMAGE_NUMBER%%%/${{ github.run_number }}/' docker-compose.template.yml > docker-compose.yml
            docker-compose up -d